
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 13
#define YY_END_OF_BUFFER 14
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[373] =
    {   0,
        0,    0,   14,   12,   11,    9,   12,    9,   12,    8,
        9,    9,    9,    9,    4,    8,    9,    9,    9,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,   12,    9,    0,
        7,    0,    0,    0,    0,    3,    3,    3,    0,    8,
        0,   10,    0,    4,    0,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    2,    2,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    2,    2,    4,    0,
        0,    0,    6,    0,    0,    5,    3,    3,    3,    3,

        0,    0,    0,    0,    0,   10,    3,    0,    3,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    2,    2,
        2,    2,    4,    6,    6,    3,    0,    0,    0,   10,
        2,    2,    2,    2,    2,    2,    2,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    2,    1,    2,    2,    2,    2,    2,

        1,    2,    2,    2,    2,    1,    1,    2,    0,    2,
        2,    2,    2,    2,    2,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    2,    2,    1,    2,    2,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    2,
        2,    2,    2,    2,    2,    1,    2,    2,    2,    2,
        1,    1,    2,    2,    2,    2,    2,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    2,    2,    2,
        2,    1,    2,    2,    2,    2,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        1,    2,    2,    2,    1,    1,    2,    1,    2,    2,
        2,    2,    1,    1,    2,    2,    1,    2,    2,    2,
        2,    2,    1,    1,    1,    1,    2,    2,    2,    2,
        1,    1,    1,    2,    2,    1,    1,    1,    2,    2,
        1,    1,    2,    1,    1,    2,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    2,    2,    1,    1,
        1,    2,    2,    2,    1,    1,    1,    2,    1,    2,
        1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        8,    9,   10,    8,   11,   12,   13,   14,   14,   15,
       16,   17,   18,   19,   19,   20,   20,   21,    8,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   49,   37,   50,
       51,   52,   53,   54,   37,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   37,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   37,   76,
       37,   77,    8,    8,    8,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    2,    1,    3,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    6,    1,    5,    5,    5,    5,
        5,    5,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1
    } ;

static const flex_int16_t yy_base[383] =
    {   0,
        0,    0,  210, 1022, 1022,  184,   75, 1022,   66, 1022,
      197,  160,  169,   80,   83,   71,  161,   82,  147,   63,
       54,   83,   74,  104,   76,   82,   88,   67,    0,  101,
      111,   74,  118,   95,  128,  123,  133,  180, 1022,  125,
     1022,  196,  178,  255,  160,  197,  217,  258,  327, 1022,
      157,    0,  224,  275,  286,    0,  130,  137,  160,  291,
      163,  179,  194,  175,  195,  196,  206,  216,  231,  241,
      246,  247,  278,  278,  287,  287,  278,  290,  289,  295,
      323,  297,  351,  302,  330,  321,  326,  326,  357,    0,
      376,  397, 1022,  157,  448, 1022,  416,  444,  460,  474,

      400,  515,    0,  122,  103,    0,  428,  521,  528,  335,
      348,  361,  378,  379,  522,  372,  382,  514,  389,  395,
      439,  416,  396,  433,  520,  410,  452,  463,  497,  497,
      522,  440,  525,  508,  514,  522,  528,  524,  519,  540,
      521,  542,  535,  536,  541,  545,  547,    0,  555,  553,
      556,  567,    0, 1022,  264,  618,  598,  118,  110, 1022,
      575,  576,  589,  593,  586,  594,  600,    0,  597,  584,
      594,  599,  599,  611,  600,  609,  602,  614,  608,  614,
      630,  619,  631,  626,  630,  625,  639,  631,  650,  651,
      634,  650,    0,  652,    0,  657,  658,  655,  645,  657,

        0,  650,  651,  654,  657,    0,    0,  673,  107,  674,
      676,  677,  677,  682,  669,    0,    0,  677,  691,  680,
      682,  687,  683,  685,  688,  698,  698,  690,  705,  697,
      701,  710,  710,  706,    0,  720,  711,    0,  712,  718,
      712,  729,  719,  734,  740,  742,  727,  743,    0,  730,
      747,  750,  738,  746,  744,    0,  758,  745,  753,  747,
        0,    0,  766,  768,  767,  774,  759,    0,  775,  776,
      769,  771,  783,  776,  790,  795,    0,  796,  798,  797,
      789,    0,  796,  794,  794,  794,    0,  812,  806,  799,
      806,  805,  821,  808,  812,  808,  820,  827,  815,  819,

        0,  823,  821,  832,    0,    0,  830,    0,  833,  825,
      833,  855,    0,    0,  845,  858,    0,  846,  851,  861,
      853,  848,    0,    0,    0,    0,  867,  854,  863,  863,
        0,    0,    0,  877,  862,    0,    0,    0,  881,  877,
        0,    0,  880,    0,    0,  890,    0,  878,  876,  880,
      884,  897,  894,  898,  904,    0,  892,  907,    0,    0,
        0,  908,  901,  901,    0,    0,    0,  898,    0,  906,
        0, 1022,  974,  981,  984,  991,  998, 1005,  104, 1012,
       91, 1016
    } ;

static const flex_int16_t yy_def[383] =
    {   0,
      372,    1,  372,  372,  372,  372,  373,  372,  374,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  372,  372,  373,
      372,  373,  376,  372,  372,  372,  372,  372,  372,  372,
      377,  378,  372,  372,  372,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  372,  379,
      373,  376,  372,  380,  380,  372,  372,  372,  372,  372,

      372,  372,  381,  377,  377,  378,  372,  372,  372,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  379,  372,  373,  372,  372,  372,  382,  372,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  372,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,    0,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372
    } ;

static const flex_int16_t yy_nxt[1101] =
    {   0,
        4,    5,    6,    7,    8,    8,    9,   10,   11,    8,
       12,   13,   14,   15,   15,   15,   15,   15,   15,   15,
       16,   17,   18,   19,    4,    8,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   30,   31,   29,
       32,   33,   29,   34,   35,   36,   29,   37,   29,   29,
        8,   38,    8,    4,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   29,   32,   33,   29,
       34,   35,   36,   29,   37,   29,   29,    8,   41,   46,
       47,   48,   48,   48,   48,   48,   42,   43,   51,   53,
       57,   50,   52,   39,   59,  159,   54,   54,   54,   54,

       54,   54,   54,   39,   64,   50,   74,   58,  153,   60,
       70,  105,   72,   96,   73,  160,   96,   49,   57,   79,
       61,   59,   71,   62,   96,   83,   44,   75,   41,   63,
      105,   39,   64,   74,   58,   76,   55,   60,   70,   65,
       72,   66,   73,   67,   80,   77,   79,   61,   68,   71,
       62,   78,   69,   83,   84,   75,   63,   87,   85,   88,
      154,   81,   86,   76,   82,  105,   96,   65,   66,   39,
       67,   39,   80,   77,  110,   68,   44,  111,   78,   69,
       50,   93,   84,   39,   94,   87,   85,   88,   81,  117,
       86,   82,   39,   89,   89,   89,   89,   89,   89,   41,

      112,  110,   94,   96,  111,   39,   39,   91,   43,  372,
       97,   97,   97,   97,   97,   97,   97,  117,  118,  121,
      119,  372,  122,   96,  120,  123,  124,  112,   90,   95,
       98,   98,   98,   98,   99,  100,  100,  107,  107,  107,
      107,  107,  107,  107,  372,  118,  121,   44,  119,  122,
       55,  125,  120,  123,  124,   90,   40,  126,   40,  127,
      372,   40,  372,  372,   96,  372,  372,   41,  372,  128,
       55,  100,  100,  100,  100,  100,  100,  100,  125,   40,
      129,   53,  372,  372,  126,  130,  131,  127,   54,   54,
       54,   54,   54,   54,   54,  108,  108,  128,  372,  109,

      109,  109,  109,  109,  109,  109,   40,  129,  136,   40,
       40,   55,  130,  131,   40,   44,  372,  372,  113,  137,
      114,   40,  132,  133,  143,   40,  134,   40,   55,   40,
       45,  135,  138,   45,  115,  116,  136,  139,  140,  147,
      101,  101,  101,  102,  102,  102,  113,  137,  114,  132,
      133,   45,  143,  134,  372,  372,  148,  141,  135,  138,
      150,  115,  116,  142,  139,  140,  147,  151,  149,  152,
       89,   89,   89,   89,   89,   89,  162,  144,   45,   41,
      161,   45,   45,  145,  148,  141,   45,  150,   43,  372,
      142,  372,  146,   45,  151,  149,  152,   45,  163,   45,

       93,   45,  103,   94,  162,  144,   96,  161,  164,  165,
      372,  145,  168,  157,  157,  157,  157,  157,  157,  146,
      372,   94,   96,  372,  177,  163,  169,   44,  172,  100,
      100,  100,  100,  100,  100,  100,  164,  165,  173,  168,
      181,  107,  107,  107,  107,  107,  107,  107,   95,   40,
       96,  155,  177,  169,   92,  172,  176,  156,  156,  156,
      156,  156,  156,  156,  372,  173,   96,  174,  181,   55,
      372,  178,   92,  156,  156,  156,  156,  156,  107,  107,
       96,   55,  182,  176,  175,  187,  372,  107,  107,  107,
      107,  107,  107,  107,  372,  174,  183,   55,  178,   92,

      372,  372,   92,   92,  372,  372,  372,   92,  372,  372,
      182,  175,  187,   55,   92,  372,  372,  372,   92,  372,
       92,   96,   92,  184,  183,  185,  372,   55,  158,  158,
      158,  158,  158,  158,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  166,  170,
      179,  184,  186,  185,  167,  188,  372,  189,  171,  190,
      180,  191,  192,  372,  193,  194,  195,  372,  196,  197,
      198,  372,  200,  201,  199,  202,  166,  170,  179,  203,
      186,  204,  167,  188,  189,  171,  190,  180,  191,  205,
      192,  193,  194,  206,  195,  196,  207,  197,  198,  200,

      201,  208,  199,  202,   96,  372,  372,  203,  372,  204,
      211,  158,  158,  158,  158,  158,  158,  205,  210,  212,
      206,  213,  215,  207,   96,  214,  216,  217,  220,  208,
      218,  107,  107,  107,  107,  107,  107,  107,  211,  219,
      221,  222,  372,  223,  226,  210,  224,  212,  225,  213,
      215,  227,  214,  228,  216,  217,  220,  218,  229,  372,
      230,  231,  372,  232,  233,  235,  219,  221,  234,  222,
      223,   55,  226,  224,  236,  225,  237,  238,  227,  239,
      228,  240,  241,  242,  243,  244,  229,  230,  245,  231,
      232,  246,  233,  235,  247,  234,  248,  249,  250,  251,

      252,  236,  253,  254,  237,  238,  239,  255,  256,  240,
      241,  242,  243,  244,  257,  245,  258,  259,  269,  246,
      261,  247,  262,  248,  249,  250,  263,  251,  252,  264,
      253,  254,  265,  266,  260,  255,  256,  267,  268,  270,
      275,  257,  271,  258,  272,  259,  269,  261,  273,  262,
      274,  276,  279,  263,  277,  278,  264,  280,  281,  265,
      266,  260,  282,  283,  267,  268,  284,  270,  275,  271,
      285,  272,  286,  287,  289,  273,  288,  274,  290,  276,
      279,  277,  278,  291,  280,  292,  281,  293,  294,  282,
      295,  283,  296,  297,  284,  298,  299,  300,  285,  286,

      301,  287,  289,  288,  302,  303,  290,  304,  372,  305,
      291,  306,  292,  307,  293,  308,  294,  295,  309,  296,
      297,  310,  311,  298,  299,  300,  312,  313,  301,  314,
      315,  302,  316,  303,  317,  304,  305,  318,  306,  319,
      322,  307,  308,  320,  321,  323,  309,  324,  328,  310,
      311,  325,  326,  327,  312,  313,  314,  329,  315,  316,
      330,  317,  331,  332,  318,  333,  334,  319,  322,  335,
      320,  321,  323,  336,  337,  324,  328,  338,  325,  326,
      327,  339,  372,  340,  341,  329,  342,  330,  343,  331,
      332,  344,  333,  345,  334,  346,  335,  347,  372,  348,

      336,  337,  349,  350,  338,  351,  372,  352,  353,  339,
      340,  354,  341,  342,  355,  343,  356,  372,  357,  344,
      345,  358,  346,  359,  360,  347,  348,  361,  363,  349,
      350,  362,  364,  351,  352,  365,  353,  366,  367,  354,
      368,  369,  355,  370,  356,  357,  371,  372,  358,  372,
      359,  360,  372,  372,  372,  361,  363,  372,  362,  372,
      364,  372,  365,  372,  372,  366,  367,  368,  369,  372,
      370,  372,  372,  371,   40,  372,   40,  372,   40,  372,
       40,   45,  372,  372,  372,   45,  372,   45,   56,  372,
       56,   92,  372,   92,   92,   92,   92,   92,  104,  104,

      104,  104,  104,  104,  104,  106,  372,  106,  106,  106,
      106,  106,   94,  372,   94,   94,   94,   94,   94,  209,
      209,    3,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372

    } ;

static const flex_int16_t yy_chk[1101] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,    9,
        9,    9,    9,    9,    9,    9,    7,    7,   14,   15,
       20,   16,   14,   16,   21,  381,   15,   15,   15,   15,

       15,   15,   15,   18,   23,   18,   28,   20,  379,   22,
       25,  105,   26,  209,   27,  105,  159,    9,   20,   32,
       22,   21,   25,   22,  158,   34,    7,   30,   40,   22,
      104,   14,   23,   28,   20,   30,   15,   22,   25,   24,
       26,   24,   27,   24,   33,   31,   32,   22,   24,   25,
       22,   31,   24,   34,   35,   30,   22,   36,   35,   37,
       94,   33,   35,   30,   33,   51,   45,   24,   24,   19,
       24,   17,   33,   31,   57,   24,   40,   58,   31,   24,
       13,   43,   35,   12,   43,   36,   35,   37,   33,   61,
       35,   33,   38,   38,   38,   38,   38,   38,   38,   42,

       59,   57,   43,   46,   58,   11,    6,   42,   42,    3,
       46,   46,   46,   46,   46,   46,   46,   61,   62,   64,
       63,    0,   64,   47,   63,   65,   66,   59,   38,   43,
       47,   47,   47,   47,   47,   47,   47,   53,   53,   53,
       53,   53,   53,   53,    0,   62,   64,   42,   63,   64,
       46,   67,   63,   65,   66,   38,   44,   68,   44,   69,
        0,   44,    0,    0,   48,    0,    0,  155,    0,   70,
       47,   48,   48,   48,   48,   48,   48,   48,   67,   44,
       70,   54,    0,    0,   68,   71,   72,   69,   54,   54,
       54,   54,   54,   54,   54,   55,   55,   70,    0,   55,

       55,   55,   55,   55,   55,   55,   44,   70,   77,   44,
       44,   48,   71,   72,   44,  155,    0,    0,   60,   78,
       60,   44,   73,   74,   82,   44,   75,   44,   54,   44,
       49,   76,   79,   49,   60,   60,   77,   80,   80,   84,
       49,   49,   49,   49,   49,   49,   60,   78,   60,   73,
       74,   49,   82,   75,    0,    0,   85,   81,   76,   79,
       86,   60,   60,   81,   80,   80,   84,   87,   85,   88,
       89,   89,   89,   89,   89,   89,  111,   83,   49,   91,
      110,   49,   49,   83,   85,   81,   49,   86,   91,    0,
       81,    0,   83,   49,   87,   85,   88,   49,  112,   49,

       92,   49,   49,   92,  111,   83,  101,  110,  113,  114,
        0,   83,  116,  101,  101,  101,  101,  101,  101,   83,
        0,   92,   97,    0,  123,  112,  117,   91,  119,   97,
       97,   97,   97,   97,   97,   97,  113,  114,  120,  116,
      126,  107,  107,  107,  107,  107,  107,  107,   92,   95,
       98,   95,  123,  117,   95,  119,  122,   98,   98,   98,
       98,   98,   98,   98,    0,  120,   99,  121,  126,   97,
        0,  124,   95,   99,   99,   99,   99,   99,   99,   99,
      100,  107,  127,  122,  121,  132,    0,  100,  100,  100,
      100,  100,  100,  100,    0,  121,  128,   98,  124,   95,

        0,    0,   95,   95,    0,    0,    0,   95,    0,    0,
      127,  121,  132,   99,   95,    0,    0,    0,   95,    0,
       95,  102,   95,  129,  128,  130,    0,  100,  102,  102,
      102,  102,  102,  102,  108,  108,  108,  108,  108,  108,
      108,  109,  109,  109,  109,  109,  109,  109,  115,  118,
      125,  129,  131,  130,  115,  133,    0,  134,  118,  135,
      125,  136,  137,    0,  138,  139,  140,    0,  141,  142,
      142,    0,  143,  144,  142,  145,  115,  118,  125,  146,
      131,  147,  115,  133,  134,  118,  135,  125,  136,  149,
      137,  138,  139,  150,  140,  141,  151,  142,  142,  143,

      144,  152,  142,  145,  157,    0,    0,  146,    0,  147,
      162,  157,  157,  157,  157,  157,  157,  149,  161,  163,
      150,  164,  166,  151,  156,  165,  167,  169,  172,  152,
      170,  156,  156,  156,  156,  156,  156,  156,  162,  171,
      173,  174,    0,  175,  178,  161,  176,  163,  177,  164,
      166,  179,  165,  180,  167,  169,  172,  170,  181,    0,
      182,  183,    0,  184,  185,  187,  171,  173,  186,  174,
      175,  156,  178,  176,  188,  177,  189,  190,  179,  191,
      180,  192,  194,  196,  197,  198,  181,  182,  199,  183,
      184,  200,  185,  187,  202,  186,  203,  204,  205,  208,

      210,  188,  211,  212,  189,  190,  191,  213,  214,  192,
      194,  196,  197,  198,  215,  199,  218,  219,  228,  200,
      220,  202,  221,  203,  204,  205,  222,  208,  210,  223,
      211,  212,  224,  225,  219,  213,  214,  226,  227,  229,
      234,  215,  230,  218,  231,  219,  228,  220,  232,  221,
      233,  236,  240,  222,  237,  239,  223,  241,  242,  224,
      225,  219,  243,  244,  226,  227,  245,  229,  234,  230,
      246,  231,  247,  248,  251,  232,  250,  233,  252,  236,
      240,  237,  239,  253,  241,  254,  242,  255,  257,  243,
      258,  244,  259,  260,  245,  263,  264,  265,  246,  247,

      266,  248,  251,  250,  267,  269,  252,  270,    0,  271,
      253,  272,  254,  273,  255,  274,  257,  258,  275,  259,
      260,  276,  278,  263,  264,  265,  279,  280,  266,  281,
      283,  267,  284,  269,  285,  270,  271,  286,  272,  288,
      291,  273,  274,  289,  290,  292,  275,  293,  297,  276,
      278,  294,  295,  296,  279,  280,  281,  298,  283,  284,
      299,  285,  300,  302,  286,  303,  304,  288,  291,  307,
      289,  290,  292,  309,  310,  293,  297,  311,  294,  295,
      296,  312,    0,  315,  316,  298,  318,  299,  319,  300,
      302,  320,  303,  321,  304,  322,  307,  327,    0,  328,

      309,  310,  329,  330,  311,  334,    0,  335,  339,  312,
      315,  340,  316,  318,  343,  319,  346,    0,  348,  320,
      321,  349,  322,  350,  351,  327,  328,  352,  354,  329,
      330,  353,  355,  334,  335,  357,  339,  358,  362,  340,
      363,  364,  343,  368,  346,  348,  370,    0,  349,    0,
      350,  351,    0,    0,    0,  352,  354,    0,  353,    0,
      355,    0,  357,    0,    0,  358,  362,  363,  364,    0,
      368,    0,    0,  370,  373,    0,  373,    0,  373,    0,
      373,  374,    0,    0,    0,  374,    0,  374,  375,    0,
      375,  376,    0,  376,  376,  376,  376,  376,  377,  377,

      377,  377,  377,  377,  377,  378,    0,  378,  378,  378,
      378,  378,  380,    0,  380,  380,  380,  380,  380,  382,
      382,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[14] =
    {   0,
0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "moronico.l"
#line 2 "moronico.l"
  #include <string.h>
  #include <stdio.h>
  #include "moronico.tab.h"
#line 909 "lex.yy.c"
#line 910 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 20 "moronico.l"


#line 1130 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 373 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1022 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "moronico.l"
{printf("línea %d, palabra reservada: %s\n", yylineno, yytext);
                                      if (strcasecmp(yytext, "abstracto") == 0) {
                                        return ABSTRACTO;
                                      } else if (strcasecmp(yytext, "asociativa") == 0){
                                        return ASOCIATIVA;
                                      } else if (strcasecmp(yytext, "booleano") == 0){
                                        return BOOLEANO;
                                      } else if (strcasecmp(yytext, "cabecera") == 0){
                                        return CABECERA;
                                      } else if (strcasecmp(yytext, "cadena") == 0){
                                        return CADENA;
                                      } else if (strcasecmp(yytext, "caso") == 0){
                                        return CASO;
                                      } else if (strcasecmp(yytext, "caracter") == 0){
                                        return CARACTER;
                                      } else if (strcasecmp(yytext, "clase") == 0){
                                        return CLASE;
                                      } else if (strcasecmp(yytext, "conjunto") == 0){
                                        return CONJUNTO;
                                      } else if (strcasecmp(yytext, "asociativa") == 0){
                                        return ASOCIATIVA;
                                      } else if (strcasecmp(yytext, "constante") == 0){
                                        return CONSTANTE;
                                      } else if (strcasecmp(yytext, "cuerpo") == 0){
                                        return CUERPO;
                                      } else if (strcasecmp(yytext, "constructor") == 0){
                                        return CONSTRUCTOR;
                                      } else if (strcasecmp(yytext, "cuando") == 0){
                                        return CUANDO;
                                      } else if (strcasecmp(yytext, "descendente") == 0){
                                        return DESCENDENTE;
                                      } else if (strcasecmp(yytext, "destructor") == 0){
                                        return DESTRUCTOR;
                                      } else if (strcasecmp(yytext, "de") == 0){
                                        return DE;
                                      } else if (strcasecmp(yytext, "devolver") == 0){
                                        return DEVOLVER;
                                      } else if (strcasecmp(yytext, "carga") == 0){
                                        return CARGA;
                                      } else if (strcasecmp(yytext, "elemento") == 0){
                                        return ELEMENTO;
                                      } else if (strcasecmp(yytext, "ejecuta") == 0){
                                        return EJECUTA;
                                      } else if (strcasecmp(yytext, "en") == 0){
                                        return EN;
                                      } else if (strcasecmp(yytext, "entero") == 0){
                                        return ENTERO;
                                      } else if (strcasecmp(yytext, "entonces") == 0){
                                        return ENTONCES;
                                      } else if (strcasecmp(yytext, "especifico") == 0){
                                        return ESPECIFICO;
                                      } else if (strcasecmp(yytext, "excepto") == 0){
                                        return EXCEPTO;
                                      } else if (strcasecmp(yytext, "fichero") == 0){
                                        return FICHERO;
                                      } else if (strcasecmp(yytext, "final") == 0){
                                        return FINAL;
                                      } else if (strcasecmp(yytext, "finalmente") == 0){
                                        return FINALMENTE;
                                      } else if (strcasecmp(yytext, "funcion") == 0){
                                        return FUNCION;
                                      } else if (strcasecmp(yytext, "generico") == 0){
                                        return GENERICO;
                                      } else if (strcasecmp(yytext, "hasta") == 0){
                                        return HASTA;
                                      } else if (strcasecmp(yytext, "interfaz") == 0){
                                        return INTERFAZ;
                                      } else if (strcasecmp(yytext, "lanzar") == 0){
                                        return LANZAR;
                                      } else if (strcasecmp(yytext, "lista") == 0){
                                        return LISTA;
                                      } else if (strcasecmp(yytext, "mientras") == 0){
                                        return MIENTRAS;
                                      } else if (strcasecmp(yytext, "modificable") == 0){
                                        return MODIFICABLE;
                                      } else if (strcasecmp(yytext, "otro") == 0){
                                        return OTRO;
                                      } else if (strcasecmp(yytext, "paquete") == 0){
                                        return PAQUETE;
                                      } else if (strcasecmp(yytext, "para") == 0){
                                        return PARA;
                                      } else if (strcasecmp(yytext, "privado") == 0){
                                        return PRIVADO;
                                      } else if (strcasecmp(yytext, "probar") == 0){
                                        return PROBAR;
                                      } else if (strcasecmp(yytext, "procedimiento") == 0){
                                        return PROCEDIMIENTO;
                                      } else if (strcasecmp(yytext, "programa") == 0){
                                        return PROGRAMA;
                                      } else if (strcasecmp(yytext, "publico") == 0){
                                        return PUBLICO;
                                      } else if (strcasecmp(yytext, "real") == 0){
                                        return REAL;
                                      } else if (strcasecmp(yytext, "registro") == 0){
                                        return REGISTRO;
                                      } else if (strcasecmp(yytext, "repite") == 0){
                                        return REPITE;
                                      } else if (strcasecmp(yytext, "salir") == 0){
                                        return SALIR;
                                      } else if (strcasecmp(yytext, "sea") == 0){
                                        return SEA;
                                      } else if (strcasecmp(yytext, "semipublico") == 0){
                                        return SEMIPUBLICO;
                                      } else if (strcasecmp(yytext, "si") == 0){
                                        return SI;
                                      } else if (strcasecmp(yytext, "sino") == 0){
                                        return SINO;
                                      } else if (strcasecmp(yytext, "tipo") == 0){
                                        return TIPO;
                                      } else if (strcasecmp(yytext, "variable") == 0){
                                        return VARIABLE;
                                      }
                                    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 137 "moronico.l"
{printf("línea %d, identificador: %s\n", yylineno, yytext); return IDENTIFICADOR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 139 "moronico.l"
{printf("línea %d, constante real: %s\n", yylineno, yytext); return CTC_REAL;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 141 "moronico.l"
{printf("línea %d, constante entera: %s\n", yylineno, yytext); return CTC_ENTERA;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 143 "moronico.l"
{printf("línea %d, caracter: %s\n", yylineno, yytext);return CTC_CARACTER;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 145 "moronico.l"
{printf("línea %d, path: %s\n", yylineno, yytext); return PATH;}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 147 "moronico.l"
{printf("línea %d, cadena: %s\n", yylineno, yytext); return CTC_CADENA;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 149 "moronico.l"
{printf("línea %d, delimitador: %s\n", yylineno, yytext);
                                      if (strcmp(yytext, "::") == 0) {
                                        return CUATRO_PTOS;
                                      } else if (strcmp(yytext, "..") == 0){
                                        return DOS_PTOS;
                                      } else if (strcmp(yytext, "=>") == 0){
                                        return FLECHA_DOBLE;
                                      } else{
                                        return yytext[0];
                                      }
                                    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 161 "moronico.l"
{printf("línea %d, operador: %s\n", yylineno, yytext);
                                      if (strcmp(yytext, "/\\") == 0) {
                                        return AND;
                                      } else if (strcmp(yytext, "->") == 0){
                                        return DESPD;
                                      } else if (strcmp(yytext, "<-") == 0){
                                        return DESPI;
                                      } else if (strcmp(yytext, ":=") == 0){
                                        return EQ;
                                      }  else if (strcmp(yytext, ">=") == 0){
                                        return GEQ;
                                      } else if (strcmp(yytext, "=<") == 0){
                                        return LEQ;
                                      } else if (strcmp(yytext, "!=") == 0){
                                        return NEQ;
                                      } else if (strcmp(yytext, "\\/") == 0){
                                        return OR;
                                      } else if (strcmp(yytext, "**") == 0){
                                        return POTENCIA;
                                      } else {
                                        return yytext[0];
                                      }
                                    }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 186 "moronico.l"
;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 190 "moronico.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 193 "moronico.l"
printf("línea %d, error: %s\n", yylineno, yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 195 "moronico.l"
ECHO;
	YY_BREAK
#line 1409 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 373 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 373 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 372);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 195 "moronico.l"

